name: [JavaScript Script] Scrape and Commit Data

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # This allows us to set up a personal access token for committing

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install  # This will install dependencies including zx if defined in package.json

      - name: Install Chrome testing browser
        run: npx @puppeteer/browsers install chrome@stable
        
      - name: Install ZX Globally
        run: npm install -global zx
      
      - name: Make script executable
        run: chmod +x ./src/scrape.mjs

      - name: Run script
        run: ./src/scrape.mjs

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit scraped data
        run: |
          git add .  # Replace with the path to your JSON files
          git commit -m "chore: Update scraped data" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
