name: JavaScript Script Scrape and Commit Data

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow
    inputs:
      year:
        description: 'The year to scrape from'
        required: true
      fromPage:
        description: 'The first page to scrape from'
        required: true
      toPage:
        description: 'The second page to scrape from'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # This allows us to set up a personal access token for committing

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install  # This will install dependencies including zx if defined in package.json

      - name: Install Chrome testing browser
        run: npx @puppeteer/browsers install chrome@stable
        
      - name: Install ZX Globally
        run: npm install -global zx
      
      - name: Make script executable
        run: chmod +x ./src/scrape.mjs

      - name: Run script
        run: ./src/scrape.mjs --year=${{ github.event.inputs.year }} --fromPage=${{ github.event.inputs.fromPage }} --toPage=${{ github.event.inputs.toPage }}

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Stage changes
        run: git add .  # Replace with the path to your JSON files

      - name: Create unique branch
        id: create_branch
        run: |
          BRANCH_NAME=scrape-${{ github.event.inputs.year }}-${{ github.event.inputs.fromPage }}-${{ github.event.inputs.toPage }}-${{ github.run_id }}
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Checkout to the new branch
        run: |
          git checkout -b ${{ env.BRANCH_NAME }}

      - name: Commit staged changes
        run: |
          git commit -m "chore: ${{ github.event.inputs.year }}, page ${{ github.event.inputs.fromPage }} - ${{ github.event.inputs.toPage }}" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          force: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "chore: ${{ github.event.inputs.year }}, page ${{ github.event.inputs.fromPage }} - ${{ github.event.inputs.toPage }}"
          branch: ${{ env.BRANCH_NAME }}
          base: main
          title: "Scrape Data: ${{ github.event.inputs.year }}, page ${{ github.event.inputs.fromPage }} - ${{ github.event.inputs.toPage }}"
          body: "This PR contains scraped data for year ${{ github.event.inputs.year }}, from page ${{ github.event.inputs.fromPage }} to ${{ github.event.inputs.toPage }}."
